[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages]
find = {}
[project]
name = "mosum"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.6"',
]
authors = [
  { name="Dom Owens", email="dom.owens@bristol.ac.uk" },
]
description = "Moving Sum Based Procedures for Changes in the Mean"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Dom-Owens-UoB/mosum.py"